import 'package:flutter_test/flutter_test.dart';
import 'package:meine_musik/env.dart';
import 'package:meine_musik/model/Playlist.dart';
import 'package:meine_musik/services/AudioApi.dart';
import 'package:meine_musik/services/MusicBrainz.dart';

import '../RecordPlaybackHttpClient.dart';

void main() {
  test('$MusicBrainz.searchReleaseByAlbum (No Angels - Elle´ments)', () async {
    musicBrainz = MusicBrainz(RecordPlaybackHttpClient());
    final album = Album.fromNameAndSongs('Elle´ments', [
      AudioFile(
        id: 18023,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/01 - No Angels - Daylight In Your Eyes.mp3',
        sizeInBytes: 3992338,
        title: 'Daylight In Your Eyes',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 210337,
      ),
      AudioFile(
        id: 18024,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/02 - No Angels - When The Angels Sing.mp3',
        sizeInBytes: 4330985,
        title: 'When The Angels Sing',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 222432,
      ),
      AudioFile(
        id: 18025,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/03 - No Angels - Promises Can Wait.mp3',
        sizeInBytes: 3745092,
        title: 'Promises Can Wait',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 201664,
      ),
      AudioFile(
        id: 18026,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/04 - No Angels - You Could Be The First.mp3',
        sizeInBytes: 3964784,
        title: 'You Could Be The First',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 204355,
      ),
      AudioFile(
        id: 18027,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/05 - No Angels - Cold As Ice.mp3',
        sizeInBytes: 4867209,
        title: 'Cold As Ice',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 246203,
      ),
      AudioFile(
        id: 18028,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/06 - No Angels - Rivers Of Joy.mp3',
        sizeInBytes: 3941740,
        title: 'Rivers Of Joy',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 208064,
      ),
      AudioFile(
        id: 18029,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/07 - No Angels - Be My Man (The Plan).mp3',
        sizeInBytes: 4209856,
        title: 'Be My Man (The Plan)',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 210755,
      ),
      AudioFile(
        id: 18030,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/08 - No Angels - Go Ahead And Take It.mp3',
        sizeInBytes: 3244798,
        title: 'Go Ahead And Take It',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 170291,
      ),
      AudioFile(
        id: 18031,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/09 - No Angels - Couldn´t Care Less.mp3',
        sizeInBytes: 4028192,
        title: 'Couldn´t Care Less',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 213890,
      ),
      AudioFile(
        id: 18032,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/10 - No Angels - Faith Can Move A Mountain.mp3',
        sizeInBytes: 4200965,
        title: 'Faith Can Move A Mountain',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 209005,
      ),
      AudioFile(
        id: 18033,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/11 - No Angels - Cry For You.mp3',
        sizeInBytes: 5612456,
        title: 'Cry For You',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 289122,
      ),
      AudioFile(
        id: 18034,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/12 - No Angels - Send Me Flowers.mp3',
        sizeInBytes: 4532526,
        title: 'Send Me Flowers',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 229093,
      ),
      AudioFile(
        id: 18035,
        path: '/storage/0000-0000/Musik/No Angels - Elle´ments/13 - No Angels - That´s The Reason.mp3',
        sizeInBytes: 3636383,
        title: 'That´s The Reason',
        artist: 'No Angels',
        album: 'Elle´ments',
        trackNumber: 0,
        durationInMilliseconds: 195761,
      ),
    ]);
    final release = await musicBrainz.searchReleaseByAlbum(album);
    expect(release?.mbid, equals('51ac4e7b-477e-4887-84fc-eee1f9fc1625'));
  });

  test('$MusicBrainz.searchReleaseByAlbum (Take That - Greatest Hits)', () async {
    musicBrainz = MusicBrainz(RecordPlaybackHttpClient());
    final album = Album.fromNameAndSongs('Greatest Hits', [
      AudioFile(
        id: 18038,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/01 - Take That - How Deep Is Your Love.mp3',
        sizeInBytes: 4373006,
        title: 'How Deep Is Your Love',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 223006,
      ),
      AudioFile(
        id: 18039,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/02 - Take That - Never Forget.mp3',
        sizeInBytes: 6964092,
        title: 'Never Forget',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 386115,
      ),
      AudioFile(
        id: 18040,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/03 - Take That - Back for Good.mp3',
        sizeInBytes: 4671830,
        title: 'Back for Good',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 243643,
      ),
      AudioFile(
        id: 18041,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/04 - Take That - Sure.mp3',
        sizeInBytes: 4038334,
        title: 'Sure',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 222876,
      ),
      AudioFile(
        id: 18042,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/05 - Take That - Love Ain’t Here Anymore.mp3',
        sizeInBytes: 4179152,
        title: 'Love Ain’t Here Anymore',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 231601,
      ),
      AudioFile(
        id: 18043,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/06 - Take That - Everything Changes.mp3',
        sizeInBytes: 4477162,
        title: 'Everything Changes',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 216006,
      ),
      AudioFile(
        id: 18044,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/07 - Take That - Babe.mp3',
        sizeInBytes: 5262045,
        title: 'Babe',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 296881,
      ),
      AudioFile(
        id: 18045,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/08 - Take That - Relight My Fire.mp3',
        sizeInBytes: 4794058,
        title: 'Relight My Fire',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 251010,
      ),
      AudioFile(
        id: 18046,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/09 - Take That - Pray.mp3',
        sizeInBytes: 4234694,
        title: 'Pray',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 225671,
      ),
      AudioFile(
        id: 18047,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/10 - Take That - Why Can’t I Wake Up With You.mp3',
        sizeInBytes: 4056209,
        title: 'Why Can’t I Wake Up With You',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 219297,
      ),
      AudioFile(
        id: 18048,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/11 - Take That - Could It Be Magic.mp3',
        sizeInBytes: 4072374,
        title: 'Could It Be Magic',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 211957,
      ),
      AudioFile(
        id: 18049,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/12 - Take That - A Million Love Songs.mp3',
        sizeInBytes: 4291586,
        title: 'A Million Love Songs',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 234317,
      ),
      AudioFile(
        id: 18050,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/13 - Take That - I Found Heaven.mp3',
        sizeInBytes: 4372606,
        title: 'I Found Heaven',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 244270,
      ),
      AudioFile(
        id: 18051,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/14 - Take That - It Only Takes a Minute.mp3',
        sizeInBytes: 4169468,
        title: 'It Only Takes a Minute',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 228649,
      ),
      AudioFile(
        id: 18052,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/15 - Take That - Once You’ve Tasted Love.mp3',
        sizeInBytes: 4289893,
        title: 'Once You’ve Tasted Love',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 225331,
      ),
      AudioFile(
        id: 18053,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/16 - Take That - Promises.mp3',
        sizeInBytes: 4304775,
        title: 'Promises',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 216946,
      ),
      AudioFile(
        id: 18054,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/17 - Take That - Do What U Like.mp3',
        sizeInBytes: 3600983,
        title: 'Do What U Like',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 189021,
      ),
      AudioFile(
        id: 18055,
        path: '/storage/emulated/0/Music/Take That - Greatest Hits/18 - Take That - Love Ain’t Here Anymore (U.S. version).mp3',
        sizeInBytes: 4418032,
        title: 'Love Ain’t Here Anymore (U.S. version)',
        artist: 'Take That',
        album: 'Greatest Hits',
        trackNumber: 0,
        durationInMilliseconds: 247431,
      ),
    ]);
    final release = await musicBrainz.searchReleaseByAlbum(album);
    expect(release?.mbid, equals('a4f1aecf-7bda-4120-a552-9afd8502a9da'));
  });
}
