// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package de.michaeltamm.meine_musik;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class AudioApi {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class AudioFile {
    private @NonNull Long id;

    public @NonNull Long getId() {
      return id;
    }

    public void setId(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    private @NonNull String path;

    public @NonNull String getPath() {
      return path;
    }

    public void setPath(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"path\" is null.");
      }
      this.path = setterArg;
    }

    private @NonNull Long sizeInBytes;

    public @NonNull Long getSizeInBytes() {
      return sizeInBytes;
    }

    public void setSizeInBytes(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sizeInBytes\" is null.");
      }
      this.sizeInBytes = setterArg;
    }

    private @NonNull String title;

    public @NonNull String getTitle() {
      return title;
    }

    public void setTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"title\" is null.");
      }
      this.title = setterArg;
    }

    private @NonNull String artist;

    public @NonNull String getArtist() {
      return artist;
    }

    public void setArtist(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"artist\" is null.");
      }
      this.artist = setterArg;
    }

    private @NonNull String album;

    public @NonNull String getAlbum() {
      return album;
    }

    public void setAlbum(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"album\" is null.");
      }
      this.album = setterArg;
    }

    private @NonNull Long trackNumber;

    public @NonNull Long getTrackNumber() {
      return trackNumber;
    }

    public void setTrackNumber(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"trackNumber\" is null.");
      }
      this.trackNumber = setterArg;
    }

    private @NonNull Long durationInMilliseconds;

    public @NonNull Long getDurationInMilliseconds() {
      return durationInMilliseconds;
    }

    public void setDurationInMilliseconds(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"durationInMilliseconds\" is null.");
      }
      this.durationInMilliseconds = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AudioFile() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AudioFile that = (AudioFile) o;
      return id.equals(that.id) && path.equals(that.path) && sizeInBytes.equals(that.sizeInBytes) && title.equals(that.title) && artist.equals(that.artist) && album.equals(that.album) && trackNumber.equals(that.trackNumber) && durationInMilliseconds.equals(that.durationInMilliseconds);
    }

    @Override
    public int hashCode() {
      return Objects.hash(id, path, sizeInBytes, title, artist, album, trackNumber, durationInMilliseconds);
    }

    public static final class Builder {

      private @Nullable Long id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull Long setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String path;

      @CanIgnoreReturnValue
      public @NonNull Builder setPath(@NonNull String setterArg) {
        this.path = setterArg;
        return this;
      }

      private @Nullable Long sizeInBytes;

      @CanIgnoreReturnValue
      public @NonNull Builder setSizeInBytes(@NonNull Long setterArg) {
        this.sizeInBytes = setterArg;
        return this;
      }

      private @Nullable String title;

      @CanIgnoreReturnValue
      public @NonNull Builder setTitle(@NonNull String setterArg) {
        this.title = setterArg;
        return this;
      }

      private @Nullable String artist;

      @CanIgnoreReturnValue
      public @NonNull Builder setArtist(@NonNull String setterArg) {
        this.artist = setterArg;
        return this;
      }

      private @Nullable String album;

      @CanIgnoreReturnValue
      public @NonNull Builder setAlbum(@NonNull String setterArg) {
        this.album = setterArg;
        return this;
      }

      private @Nullable Long trackNumber;

      @CanIgnoreReturnValue
      public @NonNull Builder setTrackNumber(@NonNull Long setterArg) {
        this.trackNumber = setterArg;
        return this;
      }

      private @Nullable Long durationInMilliseconds;

      @CanIgnoreReturnValue
      public @NonNull Builder setDurationInMilliseconds(@NonNull Long setterArg) {
        this.durationInMilliseconds = setterArg;
        return this;
      }

      public @NonNull AudioFile build() {
        AudioFile pigeonReturn = new AudioFile();
        pigeonReturn.setId(id);
        pigeonReturn.setPath(path);
        pigeonReturn.setSizeInBytes(sizeInBytes);
        pigeonReturn.setTitle(title);
        pigeonReturn.setArtist(artist);
        pigeonReturn.setAlbum(album);
        pigeonReturn.setTrackNumber(trackNumber);
        pigeonReturn.setDurationInMilliseconds(durationInMilliseconds);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(8);
      toListResult.add(id);
      toListResult.add(path);
      toListResult.add(sizeInBytes);
      toListResult.add(title);
      toListResult.add(artist);
      toListResult.add(album);
      toListResult.add(trackNumber);
      toListResult.add(durationInMilliseconds);
      return toListResult;
    }

    static @NonNull AudioFile fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AudioFile pigeonResult = new AudioFile();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((Long) id);
      Object path = pigeonVar_list.get(1);
      pigeonResult.setPath((String) path);
      Object sizeInBytes = pigeonVar_list.get(2);
      pigeonResult.setSizeInBytes((Long) sizeInBytes);
      Object title = pigeonVar_list.get(3);
      pigeonResult.setTitle((String) title);
      Object artist = pigeonVar_list.get(4);
      pigeonResult.setArtist((String) artist);
      Object album = pigeonVar_list.get(5);
      pigeonResult.setAlbum((String) album);
      Object trackNumber = pigeonVar_list.get(6);
      pigeonResult.setTrackNumber((Long) trackNumber);
      Object durationInMilliseconds = pigeonVar_list.get(7);
      pigeonResult.setDurationInMilliseconds((Long) durationInMilliseconds);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return AudioFile.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof AudioFile) {
        stream.write(129);
        writeValue(stream, ((AudioFile) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface AudioService {

    void findAll(@NonNull Result<List<AudioFile>> result);

    /** The codec used by AudioService. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `AudioService` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable AudioService api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable AudioService api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.meine_musik.AudioService.findAll" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<List<AudioFile>> resultCallback =
                    new Result<List<AudioFile>>() {
                      public void success(List<AudioFile> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.findAll(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
