# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

$build_number = number_of_commits()
$version = "0.0.#{$build_number}"

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    Dir.chdir("../..") do
      sh "make build"
    end
    upload_to_play_store(
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        version_code: $build_number,
        track: "internal",
        release_status: "draft",
    )
  end
end
